[all:vars]
ansible_user=kuromi
ansible_ssh_common_args="-o StrictHostKeyChecking=no"
ansible_ssh_private_key_file=~/.ssh/id_ed25519-skylab

[all]
web-1 ansible_host=192.168.1.110
web-2 ansible_host=192.168.1.109
db ansible_host=192.168.1.108

[db]
db ansible_host=192.168.1.108

[web]
web-1 ansible_host=192.168.1.110
web-2 ansible_host=192.168.1.109
